# Generated by Django 5.1.3 on 2024-12-22 18:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_article_scrapping_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThesisData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info', models.JSONField(null=True)),
                ('Scrap_statique_data', models.DateField(default=datetime.date.today)),
            ],
        ),
    ]
