# Generated by Django 5.1.3 on 2024-12-24 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_thesisdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='thesisdata',
            name='titre',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
