# Generated by Django 5.1.3 on 2024-12-25 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_thesisdata_titre'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='type',
            field=models.CharField(choices=[('news', 'News'), ('description', 'Description')], default='description', max_length=12),
        ),
    ]
